spring:
  profiles:
    active: hsql

---
spring:
  profiles: hsql
  datasource:
    url: jdbc:hsqldb:mem:spring-playground
    username: sa
    password: ''
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
logging:
  level:
    sql: DEBUG
    root: DEBUG
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: test
    password: 'test'
    driver-class-name: com.mysql.cj.jdbc.Driver
### hikari 사용시에 사용
#    hikari:
#      maximum-pool-size: 2
logging:
  level:
    sql: DEBUG
    root: DEBUG