spring:
  profiles:
    active: hsql

---
spring:
  profiles: hsql
  datasource:
    url: jdbc:hsqldb:mem:spring-playground
    username: sa
    password: ''
    driver-class-name: org.hsqldb.jdbcDriver
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql:localhost:3306/testdb
    username: test
    password: 'test'
    driver-class-name: com.mysql.cj.jdbc.Driver
