spring:
  profiles:
    active: mysql

---
spring:
  profiles: hsql
  datasource:
    url: jdbc:hsqldb:mem:spring-playground
    username: sa
    password: ''
    driver-class-name: org.hsqldb.jdbcDriver
logging:
  level:
    sql: DEBUG
    root: DEBUG
---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: 'test'
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    sql: DEBUG
    root: DEBUG