version: '3.3'

services:
 db:
  image: mysql:5.7
  container_name: mysql-5.7-local
  # Query Where 절에서 한글 먹히도록 하기 위해서 아래 command 추가(charset utf-8로 변환하기)
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: "testdb"
   MYSQL_USER: "test"
   MYSQL_PASSWORD: "test"
   MYSQL_ROOT_PASSWORD: "root"
